spring.application.name=project-api

spring.datasource.url=jdbc:postgresql://localhost:5432/DIMS1
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs